name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  deploy-pages:
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: ./.github/workflows/pages-build-deploy.yml
    with:
      commit_sha: ${{ github.sha }}
