name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-pages:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/pages-build-deploy.yml
    with:
      commit_sha: ${{ github.sha }}
